name: ci pipeline

on:
  push:
    branches:
      - main
      - feature/user

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name : install dependecy 
        run : mvn clean install 

      - name : run test
        run : mvn test 
